CREATE TABLE USUARIO (
USU_ID INT AUTO_INCREMENT NOT NULL,
USU_NOME VARCHAR (300) NOT  NULL,
USU_EMAIL VARCHAR (100) NOT NULL,
USU_SENHA VARCHAR (64) NOT NULL,
USU_STATUS BOOLEAN NULL DEFAULT TRUE,
USU_CARTAOSUS INT (15) NOT NULL,
CONSTRAINT PK_USU_ID PRIMARY KEY (USU_ID)
);

CREATE TABLE MEDICO(
MED_ID INT AUTO_INCREMENT NOT NULL,
MED_NOME VARCHAR (300) NOT NULL,
MED_EMAIL VARCHAR (100) NOT NULL,
MED_SENHA VARCHAR (64) NOT NULL,
MED_HOSPITAL VARCHAR (100) NOT NULL,
MED_CRM INT() NOT NULL,
CONSTRAINT PK_MED_ID PRIMARY KEY (MED_ID)
);

CREATE ESPECIALIDADE  (
ESP_ID INT AUTO_INCREMENT NOT NULL,
ESP_NOME VARCHAR (300) NOT  NULL,
CONSTRAINT PK_ESP_ID PRIMARY KEY (ESP_ID),
CONSTRAINT FK_MED_NOME FOREIGN KEY (ESP_MED_NOME), 
REFERENCES MEDICO (MED_NOME)
);

CREATE BAIRRO  (
BAI_ID INT AUTO_INCREMENT NOT NULL,
BAI_NOME VARCHAR (300) NOT  NULL,
CONSTRAINT PK_BAI_ID PRIMARY KEY (BAI_ID),
CONSTRAINT FK_MED_NOME FOREIGN KEY (BAI_MED_NOME), 
REFERENCES MEDICO (MED_NOME),
CONSTRAINT FK_MED_HOSPITAL FOREIGN KEY (BAI_MED_HOSPITAL), 
REFERENCES MEDICO (MED_HOSPITAL)
);

CREATE RESERVA  (
RES_ID INT AUTO_INCREMENT NOT NULL,
CONSTRAINT PK_RES_ID PRIMARY KEY (RES_ID),
CONSTRAINT FK_MED_NOME FOREIGN KEY (BAI_MED_NOME), 
REFERENCES MEDICO (MED_NOME),
CONSTRAINT FK_USU_NOME FOREIGN KEY (RES_USU_NOME), 
REFERENCES USURIO (USU_NOME),
);
